spring:
  datasource:
    url: jdbc:mysql://root:CwWINiWvVwibSEPHpLJW@containers-us-west-181.railway.app:7479/railway
    username: root
    password: CwWINiWvVwibSEPHpLJW
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

application: