version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "666666"
      MYSQL_DATABASE: library
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      # PMA_USER: root          # Set the root user for phpMyAdmin
      # PMA_PASSWORD: "666666"  # Set the root password for phpMyAdmin
    ports:
      - "8000:80"
    depends_on:
      - mysql


# version: ''
# services:
#   mysql:
#     image: mysql:latest
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_USER: root
#       MYSQL_DATABASE: library
#       MYSQL_ALLOW_EMPTY_PASSWORD: 1
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin:latest
#     container_name: phpmyadmin_container
#     environment:
#       PMA_PORT: 3306
#       PMA_HOST: mysql
#     ports:
#       - "8000:80"
#     depends_on:
#       - mysql
